site_name: stateless
site_description: Purely functional, Statically Typed Python
site_url: https://suned.github.io/stateless
repo_name: suned/stateless
repo_url: https://github.com/suned/stateless
edit_uri: ''
nav:
    - 'API Reference':
        - 'stateless': stateless_api.md
theme:
    name: material
    palette:
        primary: blue
    custom_dir: docs/overrides
markdown_extensions:
    - codehilite
    - admonition
plugins:
    - search
    - mkdocstrings:
        custom_templates: docs/templates
        handlers:
            python:
              options:
                show_source: false
                show_root_heading: true
        watch:
            - src/stateless
